Домашнее задание № 2
antony-g/2021-1-MAILRU-SDET-Python-A-Gladkiy pull request #2
Opened 2021-04-09 22:55 UTC by antony-g

# Домашнее задание № 2

Прошу @snicks92 или @crisscuola или @adamakalshchikov или @stpn111 проверить его.

Что было сделано:

* Составлено несколько тестов на авторизацию на портале.

* Использованы объекты класса PageObject, а также реализована авторизующаяся фикстура.

* Составлены тесты на создание рекламной компании и выбора сегмента
.

2021-04-17 13:24 UTC, snicks92 requested changes
Замечаний много, нужно многое переделать. 

1. Много лишнего кода
2. PageObject из 1 пейджы сложно назвать PageObject
3. Тесты по сути ничего не проверяют

PS. в ветке конфликт (гитхаб пишет ниже), от него надо избавиться. Исправляем конфликты в рамках этой ветки

2021-04-17 13:24 UTC, snicks92 commented on 02/code/base_tests/geckodriver.log
> +1617810493603	geckodriver	INFO	Listening on 127.0.0.1:2846
это точно нужно в репе?)

2021-04-17 13:24 UTC, snicks92 commented on 02/code/base_tests/test.py
> +        self.base_page.click(BasePageLocators.SUBMIT_BTN)
а вернуть main_page? и логично было бы сделать LoginPage и в ней метод login(user, password)

2021-04-17 13:24 UTC, snicks92 commented on 02/code/base_tests/test.py
> +        time.sleep(1)  # Ожидание завершения анимации
вместо слипа - наш вейт с попытками клика, с перехватом тех исключений что выбрасывает селениум

2021-04-17 13:24 UTC, snicks92 commented on 02/code/base_tests/test.py
> +    # @pytest.mark.skip("SKIP")
лишнее?

2021-04-17 13:24 UTC, snicks92 commented on 02/code/base_tests/test.py
> +    @pytest.mark.skip("SKIP")
skip?

2021-04-17 13:24 UTC, snicks92 commented on 02/code/base_tests/test.py
> +        self.main_page.wait().until(EC.invisibility_of_element(BasePageLocators.SPINNER_LOCATOR))
вот если бы ты не инициализировал main_page сразу в setup, а сделал бы цепочки, то главная страница у тебя бы инициализировалась строг после логина. и при ее инициализации можно было бы добавить автоматическое ожидание что спиннер пропал. а так у тебя в каждом месте эта строчка. либо вынеси это уж в поиск элемента, чтобы перед поиском и любым взаимодействием мы убеждались что нам ничего не мешает

2021-04-17 13:24 UTC, snicks92 commented on 02/code/base_tests/test.py
> +        assert input.get_attribute("value") == "https://github.com/"
а где само создание кампании то?  загрузка картинки, проверка что кампания создалась итд...

2021-04-17 13:24 UTC, snicks92 commented on 02/code/base_tests/test.py
> +        self.main_page.click(MainPageLocators.SUBMIT_SEG)
а где проверка что сегмент создался?

2021-04-17 13:24 UTC, snicks92 commented on 02/code/base_tests/test.py
> +        self.base_page.click(BasePageLocators.SUBMIT_BTN)
если ты сделал выше фикстуру логин, то чего ею не воспользоваться тут?

2021-04-17 13:24 UTC, snicks92 commented on 02/code/ui/pages/base_page.py
> +        self.wait().until(EC.invisibility_of_element(BasePageLocators.SPINNER_LOCATOR))
копипаста фикстур из тестов. и не должно быть фикстур в классе с пейджами

2021-04-17 13:24 UTC, snicks92 commented on 02/code/ui/pages/main_page.py
> +        return PythonEventsPage(self.driver)
это тут откуда?

2021-04-17 13:24 UTC, snicks92 commented on 02/code/base_tests/test.py
> +from utils.decorators import wait
импорт есть, но не используется

2021-04-17 13:24 UTC, snicks92 commented on 02/code/base_tests/test.py
> +    def test_login_neg_2(self):
этот тест очень похож на предыдущий. кажется метод логина в LoginPage решил бы эту проблему.

2021-04-17 13:24 UTC, snicks92 commented on 02/code/base_tests/test.py
> +        assert self.driver.current_url != self.base_page.url_login
кажется что тут можно еще кое что проверить, помимо того чтобы находимся на какой то странице. сообщение с ошибкой например. причем для test_login_neg_1 и test_login_neg_2 они будут разные

2021-04-17 13:24 UTC, snicks92 commented on 02/code/base_tests/test.py
> +        """Негативный тест на авторизацию"""
конкретизировать что именно негативного делается в тестах

2021-04-26 20:34 UTC, stpn111 commented
Домашку необходимо исправить до среды включительно, иначе она автоматически будет закрыта с тем количеством баллов, на которое изначально была сделана работа.

2021-04-28 20:02 UTC, antony-g commented
> 
> 
> Домашку необходимо исправить до среды включительно, иначе она автоматически будет закрыта с тем количеством баллов, на которое изначально была сделана работа.

2021-04-28 20:05 UTC, antony-g commented on 02/code/base_tests/geckodriver.log
> +1617810493603	geckodriver	INFO	Listening on 127.0.0.1:2846
Да вроде нет. Исправлено

2021-04-28 20:22 UTC, antony-g commented on 02/code/base_tests/test.py
> +        self.base_page.click(BasePageLocators.SUBMIT_BTN)
Добавил LoginPage! Спасибо за "хук"

2021-04-28 20:38 UTC, antony-g commented on 02/code/base_tests/test.py
> +        time.sleep(1)  # Ожидание завершения анимации
Исправлено

2021-04-28 20:39 UTC, antony-g commented on 02/code/base_tests/test.py
> +    # @pytest.mark.skip("SKIP")
Это я хотел для отладки запускать по одному тесту за раз

2021-04-28 20:39 UTC, antony-g commented on 02/code/base_tests/test.py
> +    @pytest.mark.skip("SKIP")
Аналогично предыдущему (skip используется для отладки)

2021-04-28 20:46 UTC, antony-g commented on 02/code/base_tests/test.py
> +        self.base_page.click(BasePageLocators.SUBMIT_BTN)
Исправлено

2021-04-28 20:48 UTC, antony-g commented on 02/code/ui/pages/base_page.py
> +        self.wait().until(EC.invisibility_of_element(BasePageLocators.SPINNER_LOCATOR))
Исправлено

2021-04-28 20:49 UTC, stpn111 commented
Закрывать PR должны преподаватели после простановки баллов...
Исправлять не планируется в итоге или ты нажал не туда?

2021-04-28 20:50 UTC, antony-g commented on 02/code/ui/pages/main_page.py
> +        return PythonEventsPage(self.driver)
Не знаю, исправил

2021-04-28 20:51 UTC, antony-g commented on 02/code/base_tests/test.py
> +from utils.decorators import wait
Исправлено

2021-04-28 20:51 UTC, antony-g commented on 02/code/base_tests/test.py
> +    def test_login_neg_2(self):
Исправлено

2021-04-28 23:26 UTC, antony-g commented on 02/code/base_tests/test.py
> +        """Негативный тест на авторизацию"""
Исправлено

2021-04-28 23:27 UTC, antony-g commented on 02/code/base_tests/test.py
> +        assert self.driver.current_url != self.base_page.url_login
Вроде try-except для ассерта - это плохая практика

2021-04-28 23:29 UTC, antony-g commented on 02/code/base_tests/test.py
> +        self.main_page.click(MainPageLocators.SUBMIT_SEG)
Проверка в самом коде (проверка на наличие соотв. div'ов. Мне кажется, или на портале произошло изменение интерфейса создания сегментов? В этот раз у меня локаторы получились совсем другие

2021-04-28 23:30 UTC, antony-g commented on 02/code/base_tests/test.py
> +        assert input.get_attribute("value") == "https://github.com/"
У меня почему-то нигде не высвечивается форма для загрузки файлов

2021-04-28 23:31 UTC, antony-g commented on 02/code/base_tests/test.py
> +        self.main_page.wait().until(EC.invisibility_of_element(BasePageLocators.SPINNER_LOCATOR))
Исправлено. Вынес в базовый "BasePage.click()" с возможностью параметризации

2021-04-28 23:38 UTC, antony-g commented on 02/code/base_tests/geckodriver.log
> +1617810493603	geckodriver	INFO	Listening on 127.0.0.1:2846
Так, вроде я добавил все лишнее в gitignore: https://github.com/antony-g/2021-1-MAILRU-SDET-Python-A-Gladkiy/blob/SDET-Python-homework-2/.gitignore
Странно, откуда опять взялись эти файлы.

2021-04-29 10:34 UTC, snicks92 commented on 02/code/base_tests/geckodriver.log
> +1617810493603	geckodriver	INFO	Listening on 127.0.0.1:2846
просто добавление в гитигнор не удаляет сами файлы, их надо удалять вручную

2021-04-29 10:36 UTC, snicks92 commented on 02/code/ui/pages/main_page.py
> +        return PythonEventsPage(self.driver)
судя по всему не исправил, по крайней мере изменений не замечено

2021-04-29 10:59 UTC, snicks92 requested changes
стало чуть чуть получше, но все еще надо доделывать. 
1. тесты написаны не до конца
2. тесты в текущем виде ничего не проверяют
3. все равно много мусора (*.pyc файлы, логи вебдрайвера, скриншоты, лишний код)
4. пейджы для кампаний и сегментов не доделаны
5. зачем то удалил из ветки код с 1 домашкой (зачем?!). если мы сейчас вмержм эту ветку в main то код твоей 1 дз пропадет. верни плиз обратно

2021-04-29 10:59 UTC, snicks92 commented on 02/code/ui/pages/login_page.py
> +        time.sleep(1)  # Пытался добавить сюда "self.wait().until(EC.invisibility_of_element(LoginPageLocators.SPINNER_LOCATOR)) из "base_page.BasePage.click()", но все время выдает TimeoutError.
здесь нужен не WebDriverWait а наш wait который будет пытаться делать ретраи

2021-04-29 10:59 UTC, snicks92 commented on 02/code/base_tests/test.py
> +        self.main_page.click(MainPageLocators.TRAFFIC_BTN, spinner=False)
это все должно быть в пеййдже кампаний. и опять же не вижу чтобы тут что то создавалось. я только что проверил, все там грузится и работает

2021-04-29 10:59 UTC, snicks92 commented on 02/code/base_tests/test.py
> +        assert MainPageLocators.SOME_NOTE is not None
`MainPageLocators.SOME_NOTE `у тебя равен `(By.CSS_SELECTOR, 'js-base-setting-note')`

tuple действительно != None. что тут проверяется то в итоге?

2021-04-29 10:59 UTC, snicks92 commented on 02/code/base_tests/test.py
> +        self.main_page.click(MainPageLocators.SEGMENT_LINK_3)
аналогично это должно быть в пейдже сегментов

название сегмента надо генерировать и прописывать при создании. затем при проверках именно по названию и искать что сегмент появился. то же самое с кампаниями

2021-04-29 10:59 UTC, snicks92 commented on 02/code/base_tests/test.py
> +        assert MainPageLocators.SEGMENT_DIV is not None
это не проверка, нужно проверять что сегмент появился в списке

2021-04-29 10:59 UTC, snicks92 commented on 02/code/base_tests/test.py
> +        assert self.driver.current_url != self.login_page.url_login
достаточно ли этих проверок? поведение сайта в test_login_neg_1 и в test_login_neg_2 отличаются, разные ошибки, разные страницы

2021-04-29 10:59 UTC, snicks92 commented on 02/code/geckodriver.log
> +1617980221493	geckodriver	INFO	Listening on 127.0.0.1:3363
до сих пор тут

2021-04-29 10:59 UTC, snicks92 commented on 02/code/utils/decorators.py
> +def wait(method, error=Exception, timeout=10, interval=0.5, check=False, **kwargs):
вот же у тебя есть наша ретраилка, но ты ей упорно не хочешь пользоваться, а пихаешь слипы

2021-04-29 10:59 UTC, snicks92 commented on 02/code/ui/fixtures.py
> +        driver.get_screenshot_as_file("last_failure.png")
зачем это, если скриншот делается в ui_report. в ветке у тебя зачем то как раз last_failure.png отсюда и прилетел

2021-04-29 11:00 UTC, snicks92 commented on 02/code/base_tests/test.py
> +        assert self.driver.current_url != self.base_page.url_login
причем тут try except?

2021-04-29 11:01 UTC, snicks92 commented on 02/code/base_tests/test.py
> +        assert input.get_attribute("value") == "https://github.com/"
проверил - все работает

2021-04-29 11:01 UTC, snicks92 commented on 02/code/base_tests/test.py
> +        self.main_page.click(MainPageLocators.SUBMIT_SEG)
изменений никаких не было, проверки я так и не увидел

2021-05-01 11:07 UTC, snicks92 commented
Принимаю как есть, так как прошло уже больше 3х недель с момента выдачи. Замечания сможешь поправить потом самостоятельно

2021-05-01 11:07 UTC, merged